"""extend exercise_templates metadata

Revision ID: 24dc40969cf7
Revises: a10dd679679e
Create Date: 2025-12-23 01:55:57.294854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24dc40969cf7'
down_revision: Union[str, Sequence[str], None] = 'a10dd679679e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_templates', sa.Column('source_id', sa.String(length=150), nullable=False))
    op.add_column('exercise_templates', sa.Column('force', sa.String(length=20), nullable=True))
    op.add_column('exercise_templates', sa.Column('level', sa.String(length=20), nullable=True))
    op.add_column('exercise_templates', sa.Column('mechanic', sa.String(length=20), nullable=True))
    op.add_column('exercise_templates', sa.Column('primary_muscles', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('exercise_templates', sa.Column('secondary_muscles', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('exercise_templates', sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_exercise_templates_source_id'), 'exercise_templates', ['source_id'], unique=True)
    op.drop_column('exercise_templates', 'muscle_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_templates', sa.Column('muscle_group', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_exercise_templates_source_id'), table_name='exercise_templates')
    op.drop_column('exercise_templates', 'instructions')
    op.drop_column('exercise_templates', 'secondary_muscles')
    op.drop_column('exercise_templates', 'primary_muscles')
    op.drop_column('exercise_templates', 'mechanic')
    op.drop_column('exercise_templates', 'level')
    op.drop_column('exercise_templates', 'force')
    op.drop_column('exercise_templates', 'source_id')
    # ### end Alembic commands ###
