"""add exercise templates and exercises

Revision ID: a10dd679679e
Revises: 6a0e2fa6410c
Create Date: 2025-12-23 01:47:58.020023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10dd679679e'
down_revision: Union[str, Sequence[str], None] = '6a0e2fa6410c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('muscle_group', sa.String(length=50), nullable=False),
    sa.Column('equipment', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tracking_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_templates_slug'), 'exercise_templates', ['slug'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_normalized', sa.String(length=200), nullable=False),
    sa.Column('muscle_group', sa.String(length=50), nullable=False),
    sa.Column('equipment', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tracking_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['exercise_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name_normalized'), 'exercises', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_exercises_template_id'), 'exercises', ['template_id'], unique=False)
    op.create_index(op.f('ix_exercises_user_id'), 'exercises', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_user_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_template_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name_normalized'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_exercise_templates_slug'), table_name='exercise_templates')
    op.drop_table('exercise_templates')
    # ### end Alembic commands ###
